# Site settings
author: Beth Ruff
title: How To Become a Software Engineer in Ten Months
header-img: img/home-bg.png
email: beth.ruff2@gmail.com
copyright_name: Beth Ruff
description: > # this means to ignore newlines until "baseurl:"
  The Ultimate Guide
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  beth-ruff

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
